sudo: required

language: cpp

branches:
  only:
    - master

services:
  - docker

matrix:
  include:
    - os: linux
      compiler: gcc
    
before_script:
  - git clone https://github.com/mcvine/resources.git mcvine-resources
  - docker pull linjiao/mcvine-ubuntu-deps:14.04

script:
  - cd docker/ubuntu/14.04/build && ./rebuild
  - cd docker/ubuntu/14.04/test && MCVINE_RESOURCES=$PWD/mcvine-resources ./run
    
notifications:
  email:
    on_success: change
    on_failure: always

