sudo: required

language: cpp

branches:
  only:
    - master

services:
  - docker

matrix:
  include:
    - os: linux
      compiler: gcc
    
before_script:
  - git clone https://github.com/mcvine/resources.git mcvine-resources
  - docker pull linjiao/mcvine-ubuntu-deps:14.04

script:
  - docker run -v `readlink -f .`:/mcvine-releaser  -e "BOOSTPYTHON_DIR=/usr" -e "BOOSTPYTHON_INCDIR=/usr/include" -e "BOOSTPYTHON_LIBDIR=/usr/lib/x86_64-linux-gnu" -e "MCVINE_RESOURCES=/mcvine-releaser/mcvine-resources" -w /mcvine-releaser linjiao/mcvine-ubuntu-deps:12.04  /bin/bash -c "python build.py && python test.py --skip-long-tests"
    
notifications:
  email:
    on_success: change
    on_failure: always

